name: API
on:
  push:
    branches: [main]
    paths:
      - 'api/**'
      - '.github/workflows/api.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: choice
        options:
          - land
          - live
        default: 'land'
jobs:
  communication:
    uses: GreyCollar/GreyCollar/.github/workflows/deploy.yml@main
    with:
      service_name: learning.api
      environment: 'live'
      context_path: ./api
      install_dependencies: true
      run_build: true
      dependency_path: ./api
      setup_config: true
    secrets:
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      DOCKER_USERNAME: centaurai
