name: UI

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: choice
        options:
          - land
          - live
        default: 'land'
jobs:
  ui:
    uses: centaurinstitute/actions/.github/workflows/deploy.yml@main
    with:
      service_name: learning.ui
      environment: 'live'
      install_dependencies: true
      run_lint: true
      run_build: true
      setup_config: true
    secrets:
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
